// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi0LyObFko-HyAL4DppPDIsZWUUWWOmzE',
    appId: '1:154668161903:web:997c9d762385d51493e69a',
    messagingSenderId: '154668161903',
    projectId: 'task-timer-63aa2',
    authDomain: 'task-timer-63aa2.firebaseapp.com',
    storageBucket: 'task-timer-63aa2.appspot.com',
    measurementId: 'G-FSBYEHZDL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEufqr0yW-gibuaGwac1OdHOISvwGi5E',
    appId: '1:154668161903:android:2fdb71659120d69293e69a',
    messagingSenderId: '154668161903',
    projectId: 'task-timer-63aa2',
    storageBucket: 'task-timer-63aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIgJa8xl3ktYEearrGKRZVvTsQFQhPS4',
    appId: '1:154668161903:ios:d6aa5c5ccf56468893e69a',
    messagingSenderId: '154668161903',
    projectId: 'task-timer-63aa2',
    storageBucket: 'task-timer-63aa2.appspot.com',
    iosClientId: '154668161903-a4amffm86r7johigl2etd8oq0oon0kqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.totoey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpIgJa8xl3ktYEearrGKRZVvTsQFQhPS4',
    appId: '1:154668161903:ios:d6aa5c5ccf56468893e69a',
    messagingSenderId: '154668161903',
    projectId: 'task-timer-63aa2',
    storageBucket: 'task-timer-63aa2.appspot.com',
    iosClientId: '154668161903-a4amffm86r7johigl2etd8oq0oon0kqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.totoey',
  );
}
